
version: 0.0
os: linux
files:
  - source: /
    destination: /app/uwajudge
hooks:
  ApplicationStop:
    - location: scripts/docker-pub-down.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/docker-pub-up.sh
      timeout: 300
      runas: root
