
version: 0.0
os: linux
files:
  - source: /
    destination: /app/nextjs
hooks:
  ApplicationStart:
    - location: scripts/start-docker.sh
    - location: scripts/start-next.sh
      timeout: 300
      runas: root
