version: '3.8'

services:
  # Database
  mariadb:
    image: mariadb
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./.mariadb:/var/lib/mysql  

  # Database Management
  phpmyadmin:
    image: phpmyadmin
    env_file:
      - .env
    environment:
      - PMA_HOST=mariadb
    ports:
      - 8080:80

  domserver:
    image: domjudge/domserver:8.2.2
    env_file:
      - .env
    environment:
      MYSQL_HOST: mariadb
    ports:
      - "8000:80"
    depends_on:
      - mariadb

  judgehost:
    image: domjudge/judgehost:8.2.2
    restart: always # TODO: give warning when fail
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./password.judgehost:/etc/password.judgehost:ro
    environment:
      DAEMON_ID: 0
      JUDGEDAEMON_PASSWORD_FILE: /etc/password.judgehost
    depends_on:
      - domserver
