version: "3.8"

services:
  # Database
  mariadb:
    image: mariadb
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - ./.mariadb:/var/lib/mysql

  # Database Management
  phpmyadmin:
    image: phpmyadmin
    env_file:
      - .env
    environment:
      PMA_HOST: mariadb
    ports:
      - 8080:80
    profiles:
      - dev

  domserver:
    image: domjudge/domserver:8.2.2
    env_file:
      - .env
    environment:
      MYSQL_HOST: mariadb
    ports:
      - "8000:80"
    depends_on:
      - mariadb

  judgehost:
    image: domjudge/judgehost:8.2.2
    restart: always # TODO: give warning when fail
    privileged: true
    # volumes:
    #   - /sys/fs/cgroup:/sys/fs/cgroup
    environment:
      DAEMON_ID: 0
      JUDGEDAEMON_PASSWORD: ${JUDGEDAEMON_PASSWORD}
    depends_on:
      - domserver
  
  problemtools:
    image: tommyjqliu/problemtools-web:latest
    ports:
      - "5000:5000"

  uwajudge:
    image: tommyjqliu/uwajudge:latest
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mariadb
    profiles:
      - prod
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/uwajudge.tommydev.net/fullchain.pem:/etc/fullchain.pem
      - /etc/letsencrypt/live/uwajudge.tommydev.net/privkey.pem:/etc/privkey.pem
    ports:
      - "80:80"
      - "443:443"
    profiles:
      - prod
    depends_on:
      - uwajudge
  

