name: Deploy to EC2

# on:
#   push:
#     branches:
#       - main  # Trigger deployment on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # specify the Node.js version you need

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build
  
    - name: Zip build output
      run: zip -r uwajudge.zip .next/standalone

    - name: Copy files via SCP
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        # SSH_HOST: ${{ secrets.SSH_HOST }}
        # SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        scp -o StrictHostKeyChecking=no standalone.zip ubuntu@3.26.80.50:~/uwajudge.zip

    # - name: Set up SSH agent
    #   uses: webfactory/ssh-agent@v0.5.3
    #   with:
    #     ssh-private-key: ${{ secrets.EC2_SSHKEY }}

    # - name: Deploy to EC2
    #   run: |
    #     ssh -o StrictHostKeyChecking=no ec2-user@3.27.217.186 '
    #     cd ~
    #     cat "version: '3.8'" > test.yml
    #     '